branches:
  only:
    - 'master'
    - 'rails3.2'
    
language: ruby
rvm:
  - 1.9.2

env:
<<<<<<< HEAD
  - DB=mysql
=======
  # - DB=postgres BUILD_TYPE=other
  - DB=mysql BUILD_TYPE=other
  # - DB=postgres BUILD_TYPE=cucumber
  - DB=mysql BUILD_TYPE=cucumber
>>>>>>> upstream/master

before_install: 
  - "./script/ci/before_install.sh"

bundler_args: "--without development production heroku"
before_script: "./script/ci/before.sh"
script: "bundle exec rake travis"

notifications:
  irc:
    channels:
      - 'irc.freenode.org:6667#diasporg'
  email:
    - tci@z8s.com

