branches:
  only:
    - 'master'

rvm:
  - 1.8.7
  - 1.9.2

env:
  - DB=postgres BUILD_TYPE=other
  - DB=mysql BUILD_TYPE=other

matrix: { exclude: [{ rvm: 1.8.7, env: DB=postgres } , { rvm: 1.9.2 , env: DB=mysql }]}

bundler_args: "--without development production"
before_script: "./config/ci/before-travis.sh"
script: "bundle exec rake travis"

notifications:
  irc:
    channels:
      - 'irc.freenode.org:6667#diasporg'
  email:
    - tci@z8s.com
