branches:
  only:
    - 'master'
    - 'develop'

language: ruby
rvm:
  - 1.9.3


env:
  - DB=mysql


bundler_args: "--without development production heroku"
before_install: "./script/ci/before_install.sh"
script: "./script/ci/build.sh"

notifications:
  email:
    - tci@z8s.com
