branches:
  only:
    - 'master'

language: ruby

rvm:
  - 2.1

env:
  - DB=mysql BUILD_TYPE=other
  - DB=mysql BUILD_TYPE=cucumber

bundler_args: "--without development production heroku"
script: "./script/ci/build.sh"

notifications:
  email:
    - tci@z8s.com
