bundler_args: "--without development production"

rvm:
  - ree
  - 1.9.2

before_script: "./config/ci/before-travis.sh"

script: "bundle exec rake travis"

env:
  - DB=postgres
  - DB=mysql

notifications:
  disable: true
