bundler_args: "--without development production"
rvm:
  - ree
  - 1.9.2

before_script:
  - "sudo aptitude -q -y install firefox"
  - "sudo cp config/ci/xvfb /etc/init.d/xvfb"
  - "sh -e /etc/init.d/xvfb start"
  - "sass --update public/stylesheets/sass/:public/stylesheets/"
  - "cp config/database.yml.example config/database.yml"
  - "rake db:create"
  - "rake db:schema:load"

script: "bundle exec rake travis"

env: "TRAVIS=true"

notifications:
  disable: true
