bundler_args: "--without development production"

rvm:
  - 1.8.7
  - ree
  - 1.9.2

before_script: "./config/ci/before-travis.sh"

script: "bundle exec rake travis"

env:
  - DB=postgres
  - DB=mysql

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: all
  irc:
    on_success: all
    on_failure: all
    channels:
      - 'irc.freenode.org#diaspora-dev'
      - 'irc.freenode.org#diaspora-de'
