language: ruby

rvm:
  - 2.2

env:
  - DB=postgresql BUILD_TYPE=other
  - DB=postgresql BUILD_TYPE=cucumber

sudo: false
cache:
  bundler: true
  directories:
    - app/assets/images

branches:
  only:
    - 'master'

before_install: gem install bundler
bundler_args: "--without development production --with mysql postgresql --jobs 3 --retry 3"

script: "./script/ci/build.sh"

notifications:
  email:
    - travis-diasporg@usr.io
