branches:
  only:
    - 'master'

  - 1.8.7
  - 1.9.2

env:
  - DB=mysql
  - DB=postgres

matrix: { exclude: [{ rvm: 1.8.7, env: DB=postgres } , { rvm: 1.9.3 , env: DB=postgres }]}
before_install: gem install bundler --pre
bundler_args: "--without development production heroku"
before_script: "./config/ci/before-travis.sh"
script: "bundle exec rake travis"

notifications:
  irc:
    channels:
      - 'irc.freenode.org:6667#diasporg'
  email:
    - tci@z8s.com
