branches:
  only:
    - 'master'

rvm:
  - 1.8.7
  - 1.9.2

env:
  - DB=postgres
  - DB=mysql

matrix:
  exclude: 
    - rvm: 1.8.7
      env:DB=postgres

bundler_args: "--without development production"
before_script: "./config/ci/before-travis.sh"
script: "bundle exec rake travis"


notifications:
  irc:
    channels:
      - 'irc.freenode.org:6667#diasporg'
