available:
  original: "Original Gray"
  original_white: "Original White Background"
  dark_green: "Dark Green"
  magenta: "Magenta"
  egyptian_blue: "Egyptian Blue"
  diasporg_wide: "Diasporg Wide Screen"
  dark: "Dark"
