#!/bin/bash
#
# rolling restart of the thins
#
export RAILS_ENV=$(./script/get_config.rb rails_env script_server)
THIN_PORT=$(./script/get_config.rb thin_port script_server)
eval "DEFAULT_THIN_ARGS=\"$(./script/get_config.rb default_thin_args script_server)\""
SOCKET_PORT=$(./script/get_config.rb socket_port $RAILS_ENV)

args="$DEFAULT_THIN_ARGS $@"

bundle exec thin restart --onebyone $args

service nginx restart
