#!/bin/bash
#
# Stop diaspora websocket and main services
#

[ -e config/server.sh ] && source config/server.sh
args="$DEFAULT_THIN_ARGS $@"

bundle exec thin stop $args
pkill -f websocket_server.rb
#pkill -f redis-server
pkill -f resque-web
pkill -f resque-1.10.0

