#!/bin/bash
#
# Stop diaspora websocket and main services
#
export RAILS_ENV=$(./script/get_config.rb rails_env script_server)
THIN_PORT=$(./script/get_config.rb thin_port script_server)
eval "DEFAULT_THIN_ARGS=\"$(./script/get_config.rb default_thin_args script_server)\""
SOCKET_PORT=$(./script/get_config.rb socket_port $RAILS_ENV)

args="$DEFAULT_THIN_ARGS $@"

bundle exec thin stop $args
pkill -f websocket_server.rb
pkill -f resque:scheduler
#pkill -f redis-server
#pkill -f resque-web
#pkill -f resque-1.10.0
#god controls workers now - god terminate to kill them
#god terminate

