#!/bin/bash
#
# Stop diaspora websocket and main services
#
export RAILS_ENV=$(./script/get_config.rb rails_env script_server)
THIN_PORT=$(./script/get_config.rb thin_port script_server)
eval "DEFAULT_THIN_ARGS=\"$(./script/get_config.rb default_thin_args script_server)\""

args="$DEFAULT_THIN_ARGS $@"

bundle exec thin stop $args
god terminate

