#!/bin/bash

function pause(){
   read -p .$*.
}
echo 'fetch upstream'
git fetch upstream
echo "Merge upstream?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) git merge upstream/master; echo 'merged git'; break;;
        No ) break;;
    esac
done
echo "push to git origin?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) git push origin master; break;;
        No ) break;;
    esac
done


echo "bundle install?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) bundle install; break;;
        No ) break;;
    esac
done

echo "Do you wish to migrate db?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) script/migrate; echo 'db migrated'; break;;
        No ) break;;
    esac
done

echo "remake assets?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) bundle exec rake assets:precompile; break;;
        No ) break;;
    esac
done




OP=`ps afx | grep 'unicorn master' | grep -v grep | awk '{ print $1 }'`
#echo $OP
echo "start new unicorn cluster?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) god restart unicorn; sleep 1m; break;;
        No ) break;;
    esac
done

#echo "cdn assets?"
#select yn in "Yes" "No"; do
#    case $yn in
#        Yes ) script/cdn; break;;
#        No ) break;;
#    esac
#done

OLD=`ps afx | grep 'unicorn master (old)' | grep -v grep | awk '{ print $1 }'`
NEW=`ps afx | grep 'unicorn master' | grep -v grep | awk '{ print $1 }'`

if [ !OLD ] 
   then
        echo "No old unicorn found!"
fi 

if [ OLD == NEW ] 
   then
	echo "oops no new unicorn is ready yet, wait longer to kill old!"
fi 

echo "kill old $OLD unicorn cluster and keep $NEW?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) kill $OLD; break;;
        No ) break;;
    esac
done

echo "notify poduptime?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) curl http://podupti.me/db/pull.php?domain=diasp.org; break;;
        No ) break;;
    esac
done



echo "restart workers?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) god restart sidekiq; break;;
        No ) break;;
    esac
done

