#!/bin/bash

function pause(){
   read -p .$*.
}
echo 'fetch upstream'
git fetch upstream
echo "Merge upstream?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) git merge upstream/master; echo 'merged git'; break;;
        No ) break;;
    esac
done
echo "push to git origin?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) git push origin master; break;;
        No ) break;;
    esac
done


echo "bundle install?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) bundle install; break;;
        No ) break;;
    esac
done

echo "Do you wish to migrate db?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) script/migrate; echo 'db migrated'; break;;
        No ) break;;
    esac
done
echo "rolling restart the thin cluster?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) script/rr; break;;
        No ) break;;
    esac
done
#god -c /root/diaspora/resque.god start resque&
echo "restart workers?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) god terminate; god -c /root/diaspora/resque.god start resque; break;;
        No ) break;;
    esac
done


echo "Jammit?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) bundle exec jammit; break;;
        No ) break;;
    esac
done
echo "cdn css/js?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) script/cdn; break;;
        No ) break;;
    esac
done
echo "notify?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) ../deploy; wget http://podupti.me/db/pull.php?domain=diasp.org >/dev/null 2>&1; break;;
        No ) break;;
    esac
done

